# Generated by Django 4.1.7 on 2023-04-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageLink',
        ),
    ]
