# Generated by Django 4.1.7 on 2023-04-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_delete_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
